apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: hrt-sre
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        ports:
        - containerPort: 3000
          name: grafana
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_INSTALL_PLUGINS
          value: ""
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: grafana-dashboard-providers
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: true
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
          readOnly: true
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: grafana
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: grafana
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-providers
        configMap:
          name: grafana-dashboard-providers
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: hrt-sre
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: grafana
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: hrt-sre
data:
  portal-red-metrics.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Portal RED Metrics",
        "tags": ["portal", "red", "sre"],
        "style": "dark",
        "timezone": "browser",
        "refresh": "30s",
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(portal_requests_total[5m]))",
                "legendFormat": "RPS"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "reqps",
                "min": 0
              }
            },
            "gridPos": {"h": 6, "w": 8, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Error Rate %",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(portal_requests_total{status=~\"5..\"}[5m])) / sum(rate(portal_requests_total[5m])) * 100",
                "legendFormat": "Error %"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "min": 0,
                "max": 100,
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": null},
                    {"color": "yellow", "value": 1},
                    {"color": "red", "value": 5}
                  ]
                }
              }
            },
            "gridPos": {"h": 6, "w": 8, "x": 8, "y": 0}
          },
          {
            "id": 3,
            "title": "Response Time P95",
            "type": "stat",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, sum(rate(portal_request_duration_seconds_bucket[5m])) by (le))",
                "legendFormat": "P95"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "s",
                "min": 0,
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": null},
                    {"color": "yellow", "value": 0.2},
                    {"color": "red", "value": 0.5}
                  ]
                }
              }
            },
            "gridPos": {"h": 6, "w": 8, "x": 16, "y": 0}
          }
        ]
      }
    }
  slo-burn-rate.json: |
    {
      "dashboard": {
        "id": null,
        "title": "SLO Burn Rate Dashboard", 
        "tags": ["slo", "sre", "burn-rate"],
        "style": "dark",
        "timezone": "browser",
        "refresh": "30s",
        "time": {
          "from": "now-6h",
          "to": "now"
        },
        "panels": [
          {
            "id": 1,
            "title": "Current Availability",
            "type": "stat",
            "targets": [
              {
                "expr": "portal:availability_ratio * 100",
                "legendFormat": "Availability"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "min": 90,
                "max": 100,
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": null},
                    {"color": "yellow", "value": 99},
                    {"color": "green", "value": 99.9}
                  ]
                }
              }
            },
            "gridPos": {"h": 6, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Error Budget Status",
            "type": "stat",
            "targets": [
              {
                "expr": "(1 - portal:error_ratio) * 100",
                "legendFormat": "Budget %"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percent",
                "min": 0,
                "max": 100,
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": null},
                    {"color": "yellow", "value": 50},
                    {"color": "green", "value": 90}
                  ]
                }
              }
            },
            "gridPos": {"h": 6, "w": 12, "x": 12, "y": 0}
          }
        ]
      }
    }