apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hrt-sre-playground
  namespace: argocd
spec:
  project: hrt-sre-playground
  source:
    repoURL: .
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hrt-sre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true