apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hrt-sre-playground
  namespace: argocd
spec:
  description: SRE Playground Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: hrt-sre
    server: https://kubernetes.default.svc
  - namespace: portal
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: batch
    kind: '*'
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: extensions
    kind: '*'