apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac.yaml
- networkpolicy.yaml
- portal.yaml
- batch-sync.yaml
- auto-healer.yaml
- mock-slack.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: hrt-sre-playground