apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-healer
  namespace: hrt-sre
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auto-healer
            env:
            - name: RESTART_THRESHOLD
              value: "2"
            - name: DRY_RUN
              value: "false"
            - name: LOG_LEVEL
              value: "debug"
            resources:
              requests:
                memory: "32Mi"
                cpu: "25m"
              limits:
                memory: "64Mi"
                cpu: "100m"