apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: portal
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: portal
        env:
        - name: FAILURE_RATE
          value: "0.05"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"